apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.kompose.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: feed-microservice
  name: feed-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: feed-microservice
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.kompose.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: feed-microservice
    spec:
      containers:
        - env:
            - name: AWS_BUCKET
              value: udagram-monolith-to-microservices
            - name: AWS_REGION
              value: us-east-1
            - name: BACKEND_PORT
              value: "8181"
            - name: ENV_TYPE
              value: developmentx
            - name: JWT_SECRET
              value: anysecret
            - name: POSTGRES_DB
              value: udagram-postgres
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USERNAME
              value: postgres
          image: rofaeilashaiaa/udagram-feed-microservice:latest
          name: feed-microservice
          ports:
            - containerPort: 8181
          resources: {}
      restartPolicy: Always
status: {}
