apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.kompose.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: reverse-proxy
  name: reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: reverse-proxy
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.kompose.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: reverse-proxy
    spec:
      containers:
        - env:
            - name: NGINX_PROXY_PORT
              value: "8080"
          image: rofaeilashaiaa/udagram-reverse-proxy:latest
          name: reverse-proxy
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
